# Generated by Django 3.2.8 on 2021-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='vaccine',
            new_name='name',
        ),
    ]
