# Generated by Django 3.2.8 on 2021-10-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_rename_vaccine_vaccine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='submission',
            new_name='submission_date',
        ),
    ]
