# Generated by Django 3.2.8 on 2021-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_auto_20211026_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccine',
            new_name='vaccinations',
        ),
    ]
